version: "3.9"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MSQL_DATABASE: TopStarters
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - "./init:/docker-entrypoint-initdb.d"

  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    restart: always
    ports:
      - 8000:8000
    environment:
      - AWS_ACCESS_KEY_ID=root
      - AWS_SECRET_ACCESS_KEY=root